@startuml
'https://plantuml.com/sequence-diagram

class TodoList{
 -ArrayList<TodoListItem> items
 -Map<String,TodoListItem>itemMap

 +void Additem(TodoListItem item);
 +void removeItem(TodoListItem item)
 +void editDueDate(String itemName, String newDate)
 +void EditDescription(String itemName, String description)
 +void MarkAsDone(String itemName)
 +void MarkAsIncomplete(String itemName)
 +void ClearList()
 +void writeFile(File file)
 +void saveFile(File file)


}
class TodoListItem{
-String description
-String dueDate
-boolean isComplete
}

TodoList *-- TodoListItem
@enduml