@startuml
'https://plantuml.com/sequence-diagram

class TodoList{
 -String description
 -String title
 -int id
 -ArrayList<TodoListItem> items

 void Additem(String desc, String dueDate);
 void removeItem(int id)
 void editDueDate(int id)
 void editDescription(int id)
 void markComplete(int id)

}
class TodoListItem{
-String description
-String dueDate
-boolean isComplete
}

TodoList *-- TodoListItem
@enduml